/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'imageUrl' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
});
export const Principal = IDL.Principal;
export const LicenseKey = IDL.Record({
  'key' : IDL.Text,
  'activatedBy' : IDL.Opt(Principal),
  'createdAt' : Time,
  'isActive' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
  'generateKey' : IDL.Func([], [IDL.Text], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllKeys' : IDL.Func([], [IDL.Vec(LicenseKey)], ['query']),
  'getBlogPostById' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserKeys' : IDL.Func([], [IDL.Vec(LicenseKey)], ['query']),
  'hasProStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'revokeKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'imageUrl' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
  });
  const Principal = IDL.Principal;
  const LicenseKey = IDL.Record({
    'key' : IDL.Text,
    'activatedBy' : IDL.Opt(Principal),
    'createdAt' : Time,
    'isActive' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
    'generateKey' : IDL.Func([], [IDL.Text], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllKeys' : IDL.Func([], [IDL.Vec(LicenseKey)], ['query']),
    'getBlogPostById' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserKeys' : IDL.Func([], [IDL.Vec(LicenseKey)], ['query']),
    'hasProStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'revokeKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };