/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Principal = Principal;
export interface LicenseKey {
    key: string;
    activatedBy?: Principal;
    createdAt: Time;
    isActive: boolean;
}
export type Time = bigint;
export interface BlogPost {
    id: bigint;
    title: string;
    content: string;
    author: string;
    imageUrl: string;
    timestamp: Time;
    category: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface AIHistoryEntry {
    id: bigint;
    toolName: string;
    input: string;
    output: string;
    timestamp: bigint;
}
export interface UserProfile {
    displayName: string;
    bio: string;
    updatedAt: bigint;
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activateKey(key: string): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkKeyValid(key: string): Promise<boolean>;
    addCustomKey(customKey: string): Promise<boolean>;
    createBlogPost(title: string, content: string, author: string, category: string, imageUrl: string): Promise<bigint>;
    deleteBlogPost(id: bigint): Promise<void>;
    generateKey(): Promise<string>;
    getAllBlogPosts(): Promise<Array<BlogPost>>;
    getAllKeys(): Promise<Array<LicenseKey>>;
    getBlogPostById(id: bigint): Promise<BlogPost>;
    getCallerUserRole(): Promise<UserRole>;
    getUserKeys(): Promise<Array<LicenseKey>>;
    hasProStatus(): Promise<boolean>;
    initialize(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    revokeKey(key: string): Promise<boolean>;
    setGroqApiKey(key: string): Promise<void>;
    callGroqAI(prompt: string, systemPrompt: string): Promise<string>;
    updateUserProfile(displayName: string, bio: string): Promise<void>;
    getUserProfile(user: Principal): Promise<UserProfile | undefined>;
    getMyProfile(): Promise<UserProfile | undefined>;
    saveAIHistory(toolName: string, input: string, output: string): Promise<bigint>;
    getMyHistory(): Promise<Array<AIHistoryEntry>>;
    clearMyHistory(): Promise<void>;
}
import type { LicenseKey as _LicenseKey, Principal as _Principal, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activateKey(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.activateKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateKey(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBlogPost(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteBlogPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async generateKey(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateKey();
            return result;
        }
    }
    async getAllBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPosts();
            return result;
        }
    }
    async getAllKeys(): Promise<Array<LicenseKey>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKeys();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKeys();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPostById(arg0: bigint): Promise<BlogPost> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostById(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserKeys(): Promise<Array<LicenseKey>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserKeys();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserKeys();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasProStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasProStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasProStatus();
            return result;
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async revokeKey(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeKey(arg0);
            return result;
        }
    }
    async checkKeyValid(arg0: string): Promise<boolean> {
        const result = await this.actor.checkKeyValid(arg0);
        return result;
    }
    async addCustomKey(arg0: string): Promise<boolean> {
        const result = await this.actor.addCustomKey(arg0);
        return result;
    }
    async setGroqApiKey(arg0: string): Promise<void> {
        await this.actor.setGroqApiKey(arg0);
    }
    async callGroqAI(arg0: string, arg1: string): Promise<string> {
        const result = await this.actor.callGroqAI(arg0, arg1);
        return result;
    }
    async updateUserProfile(arg0: string, arg1: string): Promise<void> {
        await this.actor.updateUserProfile(arg0, arg1);
    }
    async getUserProfile(arg0: any): Promise<any> {
        const result = await this.actor.getUserProfile(arg0);
        return result.length === 0 ? undefined : result[0];
    }
    async getMyProfile(): Promise<any> {
        const result = await this.actor.getMyProfile();
        return result.length === 0 ? undefined : result[0];
    }
    async saveAIHistory(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        const result = await this.actor.saveAIHistory(arg0, arg1, arg2);
        return result;
    }
    async getMyHistory(): Promise<Array<any>> {
        const result = await this.actor.getMyHistory();
        return result;
    }
    async clearMyHistory(): Promise<void> {
        await this.actor.clearMyHistory();
    }
}
function from_candid_LicenseKey_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LicenseKey): LicenseKey {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    key: string;
    activatedBy: [] | [_Principal];
    createdAt: _Time;
    isActive: boolean;
}): {
    key: string;
    activatedBy?: Principal;
    createdAt: Time;
    isActive: boolean;
} {
    return {
        key: value.key,
        activatedBy: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.activatedBy)),
        createdAt: value.createdAt,
        isActive: value.isActive
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LicenseKey>): Array<LicenseKey> {
    return value.map((x)=>from_candid_LicenseKey_n4(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
